CREATE TABLE products (
    id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    external_id bigint UNIQUE,
    title text NOT NULL CHECK (length(trim(title)) > 0),
    vendor text NOT NULL CHECK (length(trim(vendor)) > 0),
    product_type text NOT NULL CHECK (length(trim(product_type)) > 0),
    variants jsonb NOT NULL DEFAULT '[]'::jsonb,
    CHECK (jsonb_typeof(variants) = 'array')
);
